### PR TITLE
add retry to bypasse 503 error from https://extensions.gnome.org

### PR DESCRIPTION
**Pull request by thib1984**
Thank you for your great project. I installed it, but I sometimes encounter 503 errors from the site https://extensions.gnome.org/. I know this issue isn’t directly caused by your program. So, I’m submitting this PR with a retry mechanism. In the future, you could make the number of retries configurable, etc. I hope this proposal helps. Thanks again!

### CODE REVIEW

**Comment by essembeh** [comment]
Thank you very much for the PR :+1: 

Your issue needs a solution, but I'm not confortable by doing it manually, I already used [tenacity](https://github.com/jd/tenacity) on other projects and it works just fine.
I think it could be a slightly better solution: there are exponential backoff and it is not `requests` specific (I would like to rewrite `gext` to use `asyncio` and `httpx` one day ...)

What do you think?

**Comment by thib1984** [comment]
Oh great, I didn’t know about this library! It allows for cleaner code, you’re right. I’ll integrate it into my python projects. I’ve just made a new commit to address your feedback.

**Comment by essembeh** [comment]
I just pushed a branch: https://github.com/essembeh/gnome-extensions-cli/compare/http-retry?expand=1

While integrating your work, I checked and discovered `requests` has a built-in retry mechanism based on `urllib3.util.Retry`.
I prefer this solution over `tenacity` to reduce the dependency list.

Maybe you can have a look to the branch and tell me if it fits your needs?

Thanks

**Comment by thib1984** [comment]
The branch seems functional. I can’t reproduce the 503 error here, whereas it still occurs on the master branch. I agree with limiting dependencies. Sorry for not being able to provide you with a clean PR. Thank you for your feedback and your work.

**Comment by essembeh** [comment]
You're welcome, always a pleasure to receive contributions.

**Pull request closed without merging**
